DROP TABLE EMPLOYEES;
/
DROP TABLE REIMBURSEMENT; 
/
DROP TABLE RESOLVED_REIMBURSTMENT; 
/



CREATE TABLE EMPLOYEES(
    EMPLOYEE_ID INTEGER PRIMARY KEY NOT NULL,
    MANAGER_ID NUMBER,
    USERNAME VARCHAR(100),
    PASSWORDS VARCHAR(100),
    FIRSTNAME VARCHAR (100),
    LASTNAME VARCHAR (100),
    EMAIL VARCHAR2(100)

);

CREATE TABLE REIMBURSEMENT(
    REIMBURSEMENT_ID INTEGER PRIMARY KEY NOT NULL,
    EMPLOYEE_ID NUMBER,
    BALANCE DECIMAL (19,2),
    RECEIPT_IMAGE BLOB
    
);

CREATE TABLE RESOLVED_REIMBURSEMENTS(
    REIMBURSEMENT_ID INTEGER PRIMARY KEY NOT NULL,
    EMPLOYEE_ID INTEGER,
    BALANCE DECIMAL (19,2),
    RESOLVED_BY INTEGER NOT NULL,
    RECEIPT_IMAGE BLOB

);

CREATE SEQUENCE EMPLOYEE_ID_VAL 
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE REIMBURSEMENT_ID_VAL 
START WITH 10
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NEW_REIMBURSEMENT_INSERT --TRIGGER
BEFORE INSERT ON REIMBURSEMENT--TABLE
FOR EACH ROW
BEGIN 
    SELECT REIMBURSEMENT_ID_VAL.NEXTVAL--SQUENCE
    INTO :NEW.REIMBURSEMENT_ID FROM DUAL; --COLOUM
END;

CREATE OR REPLACE TRIGGER NEW_EMPLOYEE_INSERT --TRIGGER
BEFORE INSERT ON EMPLOYEES--TABLE
FOR EACH ROW
BEGIN 
    SELECT EMPLOYEE_ID_VAL.NEXTVAL--SQUENCE
    INTO :NEW.EMPLOYEE_ID FROM DUAL; --COLOUM
END;


INSERT INTO EMPLOYEES ( MANAGER_ID ,USERNAME ,PASSWORDS ,FIRSTNAME ,LASTNAME ,EMAIL )
VALUES (1,'daboi','3333','da','boy', 'shmyhol@gmail.com');


INSERT INTO EMPLOYEES ( MANAGER_ID ,USERNAME ,PASSWORDS ,FIRSTNAME ,LASTNAME ,EMAIL )
VALUES (3,'mymanager','1112','my','manager', 'mymanager@gmail.com');
/
INSERT INTO EMPLOYEES ( MANAGER_ID ,USERNAME ,PASSWORDS ,FIRSTNAME ,LASTNAME ,EMAIL )
VALUES (3,'myemployee','1111','my','employee', 'employee@gmail.com');
/
INSERT INTO REIMBURSEMENT (EMPLOYEE_ID,BALANCE )
VALUES (1020,240);

Insert INTO RESOLVED_REIMBURSEMENTS( REIMBURSEMENT_ID, EMPLOYEE_ID, BALANCE, RESOLVED_BY)
VALUES(1,1041,200,1020)
--DELETE FROM EMPLOYEES
--WHERE MANAGER_ID=1;
