 CREATE TABLE USERS_(
    USER_ID INTEGER PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(100)
);

DROP TABLE ACCOUNTS;
DROP TABLE USERS_;

 CREATE TABLE ACCOUNTS(
    ACCOUNT_ID INTEGER PRIMARY KEY NOT NULL,
    USER_ID INTEGER REFERENCES USERS_(USER_ID),
    BALANCE DECIMAL (19,2)
);


CREATE TABLE TRANSACTIONS(
    TRANS_ID INTEGER PRIMARY KEY NOT NULL,
    TRANSACTION VARCHAR(100),
    USER_ID INTEGER
);



CREATE SEQUENCE ID_VAL 
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE ACCOUNT_VAL 
START WITH 10
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NEW_USER_INSERT --TRIGGER
BEFORE INSERT ON USERS_--TABLE
FOR EACH ROW
BEGIN 
    SELECT ID_VAL.NEXTVAL--SQUENCE
    INTO :NEW.USER_ID FROM DUAL; --COLOUM
END;

CREATE OR REPLACE TRIGGER NEW_ACCOUNTS_INSERT --TRIGGER
BEFORE INSERT ON ACCOUNTS--TABLE
FOR EACH ROW
BEGIN 
    SELECT ACCOUNT_VAL.NEXTVAL--SQUENCE
    INTO :NEW.ACCOUNT_ID FROM DUAL; --COLOUM
END;


INSERT INTO USERS_(USERNAME, PASSWORD)
VALUES('ilya', 'shmyhol');


INSERT INTO USERS_(USERNAME, PASSWORD)
VALUES('randy', 'savage');


INSERT INTO USERS_(USERNAME, PASSWORD)
VALUES('luke', 'skywalker');



INSERT INTO ACCOUNTS(USER_ID,BALANCE)
VALUES (1022,10);


UPDATE ACCOUNTS SET BALANCE=15 WHERE ACCOUNT_ID=11;