 CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID NUMBER(10) PRIMARY KEY,
    EMP_FIRSTNAME VARCHAR(30) NOT NULL,
    EMP_LASTNAME VARCHAR(40) NOT NULL, 
    DEPARTMENT_ID NUMBER(10), 
    SALARY NUMBER(7,2), 
    EMP_EMAIL VARCHAR(50)
)

CREATE TABLE DEPARTMENT( 
    DEPARETMENT_ID NUMBER(10),
    DEPARTMENT_NAME VARCHAR(30)
)

CREATE SEQUENCE ENUM_SQUENCE;

CREATE OR REPLACE  TRIGGER NUMROWS 
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT ENUM_SQUENCE.NEXTVAL
    INTO :NEW.EMPLOYEE_ID
    FROM DUAL;
END;

CREATE SEQUENCE DNUM_SQUENCE;

CREATE OR REPLACE  TRIGGER DNUMROWS 
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    SELECT DNUM_SQUENCE.NEXTVAL
    INTO :NEW.DEPARTMENT_ID
    FROM DUAL;
END;

INSERT INTO EMPLOYEE(EMP_LASTNAME, EMP_FIRSTNAME,DEPARTMENT_ID,SALARY, EMP_EMAIL)
VALUES('murphy', 'diane',1,(30000.00),'dmurphy@aol.com');

INSERT INTO EMPLOYEE(EMP_LASTNAME, EMP_FIRSTNAME,DEPARTMENT_ID,SALARY, EMP_EMAIL)
VALUES('patterson','mary',1,(29000),'mpatterso@aol.com');

INSERT INTO EMPLOYEE(EMP_LASTNAME, EMP_FIRSTNAME,DEPARTMENT_ID,SALARY, EMP_EMAIL)
VALUES('firrelli', 'jeff',2,(25000.00),'jfirrelli@aol.com');

INSERT INTO EMPLOYEE(EMP_LASTNAME, EMP_FIRSTNAME,DEPARTMENT_ID,SALARY, EMP_EMAIL)
VALUES('patterson','william',2,(24000),'wpatterson@AOL.COM');

INSERT INTO EMPLOYEE(EMP_LASTNAME, EMP_FIRSTNAME,DEPARTMENT_ID,SALARY, EMP_EMAIL)
VALUES('bondur', 'gerad',3,(28000.00),'gbondur@AOL.COM');

INSERT INTO EMPLOYEE (EMP_LASTNAME, EMP_FIRSTNAME,DEPARTMENT_ID,SALARY, EMP_EMAIL)
VALUES('bow','antony',3,(29000),'abow@AOL.COM');

INSERT INTO DEPARTMENT( DEPARTMENT_NAME)
VALUES('Mangement');

INSERT INTO DEPARTMENT( DEPARTMENT_NAME)
VALUES('IT');

INSERT INTO DEPARTMENT( DEPARTMENT_NAME)
VALUES('Mangement');

CREATE OR REPLACE PROCEDURE SP_GIVE_RAISE(DEPARTMENTID IN INTEGER, NEWSALARY IN NUMBER,IS_VALID_ID OUT BOOLEAN)
IS VALID_ID NUMBER;
BEGIN
    SELECT COUNT(DEPT_ID)
    INTO DEPT_EXISTS
    FROM DEPARTMENT 
    WHERE DEPARTMENT_ID=DEPT_ID;
    IF(DEPT_EXISTS >0) THEN
        UPDATE EMPLOYEE
        SET SALARY=(SLARY*.1)+SALARY
        WHERE DEPARTMENT_ID=DEPT_ID;
        SELECT AVG(SALARY)
        INTO NEWSALARY
        FROM EMPLOYEE 
        WHERE DEPARTMENT_ID=DEPT_ID;
        END IF;
    COMMIT;
    
END;
