INSERT INTO COURSE VALUES('CISC');
INSERT INTO COURSE(COURSE_NAME) VALUES('BIO');

INSERT INTO STUDENT (FIRSTNAME, LASTNAME) VALUES ( 'Ilya', 'Shmyhol');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME) VALUES ('Tomi', 'Tomi');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME) VALUES ('Rex' ,'Rex');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME) VALUES ('Ray', 'Ray');



COMMIT;
